### ISSUE TITLE
有考虑对1.15.2进行支持吗？

### ISSUE THREAD

**Issue by xslingcn** [Lawaxi/LawaxiServerBase#1]
应该不会有太大的改动

**Comment by Lawaxi** [comment]
您好，如果您使用1.15.2或更前版本，您完全可以使用Essentials插件，它支持的功能会比ServerBase更多。您如果厌烦全家桶式服务，我想Ess的配置中支持关掉一部分内容。至少如果我自己开服会使用Ess，我的插件在1.16快照上的内容只是为了满足临时需要，在正式版出炉，Bukkit，Spigot，Ess更新后还是会放弃的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xslingcn"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月1日(星期五) 凌晨0:33
收件人:&nbsp;"Lawaxi/LawaxiServerBase"<LawaxiServerBase@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Lawaxi/LawaxiServerBase] 有考虑对1.15.2进行支持吗？ (#1)





 
应该不会有太大的改动

**Comment by xslingcn** [comment]
Ess插件目前好像没有对fabric的支持？

**Comment by xslingcn** [comment]
其实我主要是想要一个能在fabric上使用的基础插件，Spigot对游戏特性做出了不少修改这点令我很头疼...
